Fixed tabs at pdl

diff --git a/pdl/pdl b/pdl/pdl
--- a/pdl/pdl
+++ b/pdl/pdl
@@ -2,15 +2,15 @@
 
 while getopts "p:f:" opt
 do
-case $opt in
-p) pid=$OPTARG;;
-f) file_load=$OPTARG;;
-esac
-done	
+    case $opt in
+	p) pid=$OPTARG;;
+	f) file_load=$OPTARG;;
+    esac
+done
 
 
 if [ -f "$file_load" ]; then
-	load_stat="$(
+    load_stat="$(
 sudo gdb -n -q -batch \
   -ex "attach $pid" \
   -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
@@ -19,15 +19,15 @@ sudo gdb -n -q -batch \
   -ex "quit"
 )"
 else
-echo "Couldn't find file"
-exit 1
+    echo "Couldn't find file"
+    exit 1
 fi
 
 last_line="${load_stat##*$'\n'}"
 
 if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
-echo Load status: success
+    echo Load status: success
 else
-echo Load status: failure
-exit 1
+    echo Load status: failure
+    exit 1
 fi
